spring:
  application:
    name: organaiz
  datasource:
    url: jdbc:postgresql://localhost:5432/Organaiz_db
    username: postgres
    password: idealnaz
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: organaiz
      password: organaiz

organaiz:
  security:
    jwt-secret-key: "01ffcb07d72f292ff092bda98d15c241542dbb69ac64caae8e3fa18efc2fd53136b8f3090ea1a7e2b1cd2ae082974e9178ec2ffd944d78605f4c371079bf9bd7"

